Satori/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('dashboard.urls')),
    path('contracts/', include('contracts.urls')),
    path('admin/', admin.site.urls),
    path('templates/', include('templateStorage.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templateStorage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('delete', views.delete, name='delete')
]

templateStorage/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.forms import ModelForm, Textarea, TextInput, FileInput, ModelChoiceField, Select


# Create your models here.

class ContractCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    original_file = models.FileField(upload_to='templates/', validators=[FileExtensionValidator(allowed_extensions=['docx'])])
    text_content = models.TextField(null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    category = models.ForeignKey(ContractCategory, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ContractTemplateForm(ModelForm):
    category = ModelChoiceField(queryset=ContractCategory.objects.all(), widget=Select(attrs={'class': 'form-control'}),
                                empty_label="(Nothing)")

    class Meta:
        model = ContractTemplate
        fields = ['name', 'description', 'category', 'original_file']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'description': TextInput(attrs={'class': 'form-control'}),
            'original_file': FileInput(attrs={'class': 'form-control'})
        }
        labels = {
            'name': 'Name of the template',
            'description': 'Description of this template',
            'original_file': 'Choose a file (.docx)',
            'category': 'Choose a category for this template'
        }

templateStorage/views.py
from django.shortcuts import render
from .models import ContractTemplate, ContractTemplateForm, ContractCategory
from django.http import HttpResponseRedirect
from mammoth import extract_raw_text


# Create your views here.
def index(request):
    if request.method == 'POST':
        form = ContractTemplateForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save(commit=False)

            # process the form data to extract the word document text

            obj.text_content = extract_raw_text(obj.original_file).value
            obj.save()

            return HttpResponseRedirect('/templates')
    else:
        form = ContractTemplateForm()

    categories = ContractCategory.objects.all()
    context = {'categories': categories, 'form': form}

    return render(request, 'templateStorage/index.html', context)


def delete(request):
    ContractTemplate.objects.filter(id=request.GET.get('id', '')).delete()
    return HttpResponseRedirect('/templates')

templateStorage/templates/templateStorage/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% for category in categories %}
    <div class="card">
        <div class="card-header">
            <b>{{ category.name }} Templates</b>
        </div>
        <div class="card-body">
            <table class="table table-responsive-sm table-striped">
                <thead>
                    <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Last Updated</th>
                    <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    {% for template in category.contracttemplate_set.all %}
                        <tr>
                            <td>{{ template.name }}</td>
                            <td>{{ template.description }}</td>
                            <td>{{ template.created_at }}</td>
                            <td>
                                <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#template{{ template.id }}" ><i class="icon-eye"></i></a>
                                <a href="{{ template.original_file.url }}" class="btn btn-sm btn-primary" target="_blank"><i class="icon-cloud-download"></i></a>
                                <a href="/templates/delete?id={{ template.id }}" class="btn btn-sm btn-primary" ><i class="icon-trash"></i></a>
                            </td>
                        </tr>

                        <div class="modal fade" id="template{{ template.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{{ template.name }}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                    </button>
                </div>

                    <div class="modal-body">
                        <textarea disabled class="form-control" style="width: 100%;" rows="30">{{ template.text_content }}</textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endfor %}


{% endblock %}

{% block scripts %}
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Upload a new contract template</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                    </button>
                </div>

                    <div class="modal-body">
                        <form method="post" id="form" enctype='multipart/form-data' novalidate>
                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" onclick="$('#form').submit();">Submit</button>
                    </div>

                </div>
            </div>
        </div>


{% endblock %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Satori</li>
        <li class="breadcrumb-item active">Templates</li>
        <li class="breadcrumb-item">
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#largeModal">
                Upload new template
            </button>
        </li>
        <li class="breadcrumb-item">
            <input type="text" class="form-control-sm" placeholder="Search">
        </li>
{% endblock %}